spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/beorg
    username: postgres
    password: postgres

prices:
  url: http://localhost:8081

percent: 40

#spring:
#  jpa:
#    hibernate:
#      ddl-auto: create

